const eras={
'الجاهلي':{text:'نشأ الشعر الجاهلي في بيئة صحراوية قبل الإسلام، وكانت القبيلة محور الحياة. امتاز بجزالة الألفاظ وقوة التصوير وصدق التعبير عن الفروسية والكرم والحكمة والحنين.',poets:['امرؤ القيس','عنترة بن شداد','زهير بن أبي سلمى'],q:'كيف أثرت الصحراء وحياة القبيلة في صور الشاعر الجاهلي وألفاظه؟'},
'صدر الإسلام':{text:'تأثر الشعر في صدر الإسلام بالقيم الإسلامية الجديدة، فبرز الدفاع عن الدعوة والقيم الأخلاقية وهدأت بعض أغراض الجاهلية.',poets:['حسان بن ثابت','كعب بن زهير'],q:'ما التغير الذي تتوقع حدوثه في موضوعات الشعر بعد ظهور الإسلام؟'},
'الأموي':{text:'اتسعت الدولة الأموية وتعددت البيئات السياسية والاجتماعية، فازدهرت النقائض والغزل والشعر السياسي.',poets:['جرير','الفرزدق','الأخطل','جميل بثينة'],q:'لماذا ازدهر الشعر السياسي والنقائض في العصر الأموي؟'},
'العباسي':{text:'شهد العصر العباسي ازدهار المدن والعلوم والترجمة واختلاط الثقافات، فظهر التجديد في المعاني والصور والأساليب.',poets:['المتنبي','أبو تمام','البحتري','أبو نواس','أبو العتاهية'],q:'كيف يمكن لازدهار المدن والعلوم أن يغيّر لغة الشعر وموضوعاته؟'},
'الأندلسي':{text:'نشأ الشعر الأندلسي في بيئة غنية بالطبيعة والحدائق والعمران، فكثر وصف الطبيعة ورقّت الألفاظ وظهر فن الموشحات.',poets:['ابن زيدون','ابن خفاجة','لسان الدين بن الخطيب'],q:'ما العلاقة بين جمال الطبيعة في الأندلس وكثرة الوصف في شعرها؟'},
'النهضة':{text:'سعى شعراء النهضة إلى إحياء قوة الشعر العربي القديم مع معالجة قضايا الوطن والإصلاح والتعليم.',poets:['محمود سامي البارودي','أحمد شوقي','حافظ إبراهيم'],q:'كيف جمع شعراء النهضة بين التراث وقضايا عصرهم؟'},
'الحديث والمعاصر':{text:'شهد الشعر الحديث تحولات في الشكل والصورة واللغة، وبرز شعر التفعيلة إلى جانب القصيدة العمودية وقضايا الإنسان والوطن والهوية.',poets:['بدر شاكر السياب','نازك الملائكة','محمود درويش'],q:'ما الذي قد يدفع شاعرًا حديثًا إلى البحث عن شكل شعري جديد؟'}
};
const poetInfo={
'المتنبي':{era:'العباسي',text:'المتنبي أحمد بن الحسين من أشهر شعراء العصر العباسي. ارتبط شعره بالطموح والفخر والحكمة وقوة الشخصية، وتمتاز عبارته بكثافة المعنى وقوة الصياغة.',q:'برأيك لماذا بقيت حكم المتنبي حاضرة في الثقافة العربية حتى اليوم؟'},
'عنترة بن شداد':{era:'الجاهلي',text:'عنترة بن شداد شاعر وفارس جاهلي. جمع شعره بين الفروسية والحب والفخر، وكانت تجربته الشخصية مرتبطة بإثبات مكانته وشجاعته.',q:'كيف اجتمعت الفروسية والعاطفة في شخصية عنترة وشعره؟'},
'أحمد شوقي':{era:'النهضة',text:'أحمد شوقي من أبرز شعراء النهضة، ولقّب بأمير الشعراء. جمع في شعره بين المحافظة على البناء العربي القديم والاهتمام بالتاريخ والوطن والمسرح الشعري.',q:'كيف يمكن لشاعر أن يحافظ على التراث ويعبّر في الوقت نفسه عن عصره؟'},
'محمود درويش':{era:'الحديث والمعاصر',text:'محمود درويش من أبرز شعراء العربية المعاصرين، وارتبط شعره بالوطن والهوية والذاكرة والإنسان، مع تطور واضح في الصورة والبناء الشعري.',q:'كيف تتحول تجربة الوطن في الشعر من موضوع سياسي إلى تجربة إنسانية؟'}
};
let mode='explore', currentEra=null, currentPoet=null, conversation=[];
const $=s=>document.querySelector(s), voice=$('.voice'), state=$('#state'), status=$('#status'), transcript=$('#transcript'), answer=$('#answer'), prompt=$('#prompt'), erasEl=$('#eras'), poetsEl=$('#poets');
function setState(s,label){voice.classList.remove('listening','thinking','speaking');state.className='state '+s;if(s!=='idle')voice.classList.add(s);state.textContent=label}
function say(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='ar-AE';u.rate=.9;u.onstart=()=>setState('speaking','يتحدث');u.onend=()=>setState('idle','جاهز');speechSynthesis.speak(u)}
function respond(text,q='',speak=true){answer.textContent=text;prompt.textContent=q?'سؤالي لك: '+q:'';conversation.push({role:'assistant',text});if(speak)say(text+(q?' '+q:''))}
function renderPoets(era){poetsEl.innerHTML='';(eras[era]?.poets||[]).forEach(name=>{const b=document.createElement('button');b.className='poet';b.textContent=name;b.onclick=()=>openPoet(name);poetsEl.appendChild(b)})}
Object.keys(eras).forEach(name=>{const b=document.createElement('button');b.className='era';b.textContent='العصر '+name;b.onclick=()=>showEra(name,b);erasEl.appendChild(b)});
function showEra(name,b){currentEra=name;currentPoet=null;document.querySelectorAll('.era').forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');renderPoets(name);respond(eras[name].text+' من أبرز شعرائه: '+eras[name].poets.join('، ')+'.',eras[name].q)}
function openPoet(name){currentPoet=name;const info=poetInfo[name]||{era:currentEra,text:name+' من شعراء العصر '+(currentEra||'العربي')+'. يمكنني مناقشة سياقه الأدبي وسمات عصره ومقارنته بغيره.',q:'ما الجانب الذي تريد استكشافه في هذا الشاعر؟'};currentEra=info.era;respond(info.text,info.q)}
function compare(a,b){const ia=poetInfo[a],ib=poetInfo[b];if(ia&&ib){respond('عند المقارنة بين '+a+' و'+b+' نلاحظ اختلاف السياق التاريخي والبيئة والموضوعات. '+a+' ينتمي إلى '+ia.era+'، بينما '+b+' ينتمي إلى '+ib.era+'. المقارنة الأدبية الجيدة تنظر إلى البيئة واللغة والصورة والغرض الشعري لا إلى الشهرة فقط.','ما أوجه التشابه والاختلاف التي لاحظتها أنت؟');return}respond('للمقارنة الجيدة اختر شاعرين أو عصرين، وسنقارن البيئة والموضوعات واللغة والصورة والأسلوب.','من تريد أن أقارن؟')}
function quiz(){const era=currentEra||'العباسي';mode='quiz';$('#agentMode').textContent='وضع الاختبار الشفهي';respond('حسنًا، سنبدأ اختبارًا شفهيًا قصيرًا في العصر '+era+'. أجب بصوتك، وسأبني السؤال التالي على إجابتك.',eras[era].q)}
function simulate(name){mode='poet';$('#agentMode').textContent='محاكاة تعليمية لشخصية شعرية';currentPoet=name;const info=poetInfo[name];if(info){respond('محاكاة تعليمية: أهلاً بك. سنتحاور الآن كما لو أنك تجري مقابلة أدبية مع '+name+'. هذه الإجابات تفسير تعليمي وليست أقوالًا تاريخية حرفية. '+info.text,'ما أول سؤال تريد أن تطرحه على '+name+'؟')}else respond('اختر شاعرًا من الشجرة أولًا، ثم اطلب مني بدء المحاكاة التعليمية.','أي شاعر تريد؟')}
function handle(t){conversation.push({role:'user',text:t});transcript.textContent='أنت: '+t;setState('thinking','يفكر');setTimeout(()=>{let era=Object.keys(eras).find(k=>t.includes(k));if(t.includes('اختبر'))return quiz();if(t.includes('قارن')){const names=Object.keys(poetInfo).filter(n=>t.includes(n));if(names.length>=2)return compare(names[0],names[1]);return compare();}if(t.includes('تحدث مع')||t.includes('حاور')||t.includes('محاكاة')){const n=Object.keys(poetInfo).find(x=>t.includes(x))||currentPoet;return simulate(n)}const p=Object.keys(poetInfo).find(n=>t.includes(n));if(p)return openPoet(p);if(era)return showEra(era);if(t.includes('مصدر')||t.includes('ابحث')){setState('thinking','يبحث');return respond('ميزة البحث الخارجي الموثق جاهزة في الواجهة، لكنها تحتاج ربط مفتاح خدمة بحث أو نموذج ذكاء اصطناعي من الخادم قبل أن أعرض مصادر حية. لن أضع أي مفتاح سري داخل المتصفح أو GitHub.','هل تريد متابعة الشرح من قاعدة المعرفة الحالية؟')};if(mode==='quiz'&&currentEra)return respond('وصلت إجابتك: «'+t+'». الآن حاول أن تربط إجابتك ببيئة العصر '+currentEra+'.',eras[currentEra].q);respond('فهمت سؤالك: «'+t+'». يمكنني حاليًا متابعته ضمن العصور والشعراء الموجودين في قاعدة المعرفة، أو تحويله إلى مقارنة أو اختبار أو محاكاة تعليمية.','هل تريد شرحًا أم مقارنة أم اختبارًا؟')},420)}
$('.modes').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('.modes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;const labels={explore:'وضع الاستكشاف',debate:'وضع المناقشة',quiz:'وضع الاختبار الشفهي',compare:'وضع المقارنة',poet:'محاكاة شخصية شعرية'};$('#agentMode').textContent=labels[mode];if(mode==='quiz')quiz();else if(mode==='poet')simulate(currentPoet);else respond('تم تفعيل '+labels[mode]+'. تحدث معي الآن وسأتابع معك في نفس السياق.','ما الذي تريد أن نبدأ به؟')});
$('#speak').onclick=()=>say(answer.textContent+' '+prompt.textContent);$('#interrupt').onclick=()=>{speechSynthesis.cancel();setState('idle','جاهز');status.textContent='تم إيقاف الراوي. يمكنك المقاطعة والتحدث الآن.'};$('#toggleTree').onclick=()=>{erasEl.hidden=!erasEl.hidden;poetsEl.hidden=erasEl.hidden};$('#send').onclick=()=>{const v=$('#command').value.trim();if(v){handle(v);$('#command').value=''}};$('#command').addEventListener('keydown',e=>{if(e.key==='Enter')$('#send').click()});
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec;if(SR){rec=new SR();rec.lang='ar-AE';rec.interimResults=true;rec.continuous=false;rec.onstart=()=>{setState('listening','يستمع');status.textContent='أستمع إليك الآن…'};rec.onresult=e=>{let final='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)final+=e.results[i][0].transcript;else transcript.textContent='أنت: '+e.results[i][0].transcript+'…'}if(final)handle(final)};rec.onerror=()=>{setState('idle','جاهز');status.textContent='تعذر التقاط الصوت. جرّب مرة أخرى.'};rec.onend=()=>{if(!voice.classList.contains('thinking')&&!voice.classList.contains('speaking'))setState('idle','جاهز');status.textContent='اضغط الميكروفون وتحدث بحرية'};$('#mic').onclick=()=>{speechSynthesis.cancel();rec.start()}}else{$('#mic').disabled=true;$('#mic').textContent='التعرف الصوتي غير مدعوم';status.textContent='استخدم Chrome أو Edge لتجربة المحادثة الصوتية'}
setTimeout(()=>say('مرحبًا بك في شجرة الشعراء. أنا مساعدك الذكي في رحلة عبر عصور الشعر العربي. فبأي عصر نبدأ رحلتنا؟'),700);