const eras={
'الجاهلي':{text:'نشأ الشعر الجاهلي في بيئة صحراوية قبل الإسلام، وكانت القبيلة محور الحياة. امتاز بجزالة الألفاظ، وقوة التصوير، وصدق التعبير عن الفروسية والكرم والحكمة والحنين. من أبرز شعرائه امرؤ القيس وعنترة بن شداد وزهير بن أبي سلمى.',q:'كيف تتوقع أن تؤثر الصحراء وحياة القبيلة في صور الشاعر الجاهلي وألفاظه؟'},
'صدر الإسلام':{text:'تأثر الشعر في صدر الإسلام بالقيم الجديدة والقرآن الكريم، فخفّت بعض أغراض الجاهلية وبرز الدفاع عن الدعوة والقيم الأخلاقية. من أبرز الشعراء حسان بن ثابت وكعب بن زهير.',q:'ما التغير الذي تتوقع حدوثه في موضوعات الشعر بعد ظهور الإسلام؟'},
'الأموي':{text:'اتسعت الدولة الأموية وتعددت البيئات السياسية والاجتماعية، فازدهر النقائض والغزل بنوعيه العذري والصريح والشعر السياسي. من أشهر الشعراء جرير والفرزدق والأخطل وجميل بثينة.',q:'لماذا برأيك ازدهر الشعر السياسي والنقائض في العصر الأموي؟'},
'العباسي':{text:'شهد العصر العباسي حضارة واسعة واختلاط ثقافات وازدهار العلوم والمدن، فظهر التجديد في المعاني والصور والأساليب. من أبرز شعرائه أبو نواس وأبو تمام والبحتري والمتنبي وأبو العتاهية.',q:'كيف يمكن لازدهار المدن والعلوم أن يغيّر لغة الشعر وموضوعاته؟'},
'الأندلسي':{text:'نشأ الشعر الأندلسي في بيئة غنية بالطبيعة والحدائق والعمران، فكثر وصف الطبيعة ورقّت الألفاظ وظهر فن الموشحات. من شعرائه ابن زيدون وابن خفاجة ولسان الدين بن الخطيب.',q:'ما العلاقة بين جمال الطبيعة في الأندلس وكثرة الوصف في شعرها؟'},
'النهضة':{text:'سعى شعراء النهضة إلى إحياء قوة الشعر العربي القديم مع معالجة قضايا عصرهم والوطن والإصلاح. من أبرزهم محمود سامي البارودي وأحمد شوقي وحافظ إبراهيم.',q:'كيف جمع شعراء النهضة بين التراث وقضايا عصرهم؟'},
'الحديث والمعاصر':{text:'شهد الشعر الحديث والمعاصر تحولات كبيرة في الشكل والصورة واللغة، وبرز الشعر الحر وقصيدة التفعيلة إلى جانب القصيدة العمودية، مع حضور قضايا الإنسان والوطن والهوية. من الأسماء البارزة بدر شاكر السياب ونازك الملائكة ومحمود درويش.',q:'ما الذي قد يدفع شاعرًا حديثًا إلى البحث عن شكل شعري جديد؟'}
};
const $=s=>document.querySelector(s), erasEl=$('#eras'), answer=$('#answer'), prompt=$('#prompt'), transcript=$('#transcript'), status=$('#status'), voice=$('.voice');
Object.keys(eras).forEach(name=>{const b=document.createElement('button');b.className='era';b.textContent='العصر '+name;b.onclick=()=>showEra(name,b);erasEl.appendChild(b)});
function showEra(name,b){document.querySelectorAll('.era').forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');answer.textContent=eras[name].text;prompt.textContent='سؤالي لك: '+eras[name].q;say(eras[name].text+' '+eras[name].q)}
function say(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='ar-AE';u.rate=.9;speechSynthesis.speak(u)}
$('#speak').onclick=()=>say(answer.textContent+' '+prompt.textContent);
function respond(t){transcript.textContent='أنت: '+t;let key=Object.keys(eras).find(k=>t.includes(k));if(key){showEra(key);return}if(t.includes('المتنبي')){answer.textContent='المتنبي هو أحمد بن الحسين، من أعلام الشعر العباسي. ارتبط شعره بقوة الشخصية والطموح والحكمة والفخر، وتمتاز لغته بالقوة وكثافة المعنى.';prompt.textContent='سؤالي لك: لماذا تعتقد أن الحكمة بقيت من أكثر جوانب شعر المتنبي حضورًا حتى اليوم؟';say(answer.textContent+' '+prompt.textContent);return}if(t.includes('عنترة')){answer.textContent='عنترة بن شداد شاعر وفارس جاهلي، جمع شعره بين الفروسية والحب والفخر، وارتبطت تجربته الشخصية بسعيه إلى إثبات مكانته وشجاعته.';prompt.textContent='سؤالي لك: كيف اجتمعت الفروسية والعاطفة في شخصية عنترة وشعره؟';say(answer.textContent+' '+prompt.textContent);return}answer.textContent='سمعت سؤالك. في هذه النسخة التجريبية أستطيع محاورتك حول العصور الشعرية والمتنبي وعنترة، وسنوسّع المعرفة والبحث الموثق في النسخة المتصلة بالذكاء الاصطناعي.';prompt.textContent='جرّب أن تقول: قارن بين العصر الجاهلي والعصر العباسي.';say(answer.textContent)}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec;if(SR){rec=new SR();rec.lang='ar-AE';rec.interimResults=false;rec.onstart=()=>{voice.classList.add('listening');status.textContent='أستمع إليك الآن…'};rec.onend=()=>{voice.classList.remove('listening');status.textContent='اضغط وابدأ الحديث'};rec.onerror=()=>{status.textContent='تعذر التقاط الصوت. جرّب مرة أخرى.'};rec.onresult=e=>respond(e.results[0][0].transcript);$('#mic').onclick=()=>rec.start()}else{$('#mic').disabled=true;$('#mic').textContent='التعرف الصوتي غير مدعوم في هذا المتصفح';status.textContent='استخدم Chrome أو Edge لتجربة الصوت'}
setTimeout(()=>say('مرحبًا بك في شجرة الشعراء. أنا مساعدك الذكي في رحلة عبر عصور الشعر العربي. فبأي عصر نبدأ رحلتنا؟'),700);